<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40444" started-at="2020-05-29T19:45:46Z" finished-at="2020-05-29T19:46:27Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests1.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:TestRunner.TestRunner@7fac631b]" name="feature" class="TestRunner.AbstractTestNGCucumberTests1"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="40444" started-at="2020-05-29T19:45:46Z" finished-at="2020-05-29T19:46:27Z">
      <class name="TestRunner.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:TestRunner.TestRunner@7fac631b]" test-instance-name="" name="setUpClass" is-config="true" duration-ms="174" started-at="2020-05-30T01:15:46Z" finished-at="2020-05-30T01:15:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method name="feature" test-instance-name="" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:TestRunner.TestRunner@7fac631b]" status="FAIL" duration-ms="40174" finished-at="2020-05-30T01:16:27Z" started-at="2020-05-30T01:15:47Z" data-provider="features" description="Runs Cucumber Feature">
          <params>
            <param index="0">
              <value>
                <![CDATA[To Automate AEM]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at TestRunner.AbstractTestNGCucumberTests1.feature(AbstractTestNGCucumberTests1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at stepDefinitions.AEMauthor.add_the_component(AEMauthor.java:506)
	at âœ½.Then add the component "KAW Image" to 3(AEMauthor.feature:55)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:TestRunner.TestRunner@7fac631b]" test-instance-name="" name="tearDownClass" is-config="true" duration-ms="7" started-at="2020-05-30T01:16:27Z" finished-at="2020-05-30T01:16:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
